global:
  scrape_interval: 20s

  external_labels:
    monitor: 'code-lab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 10s

    static_configs:
      - targets: ['localhost:9090']